### ISSUE TITLE
Candidate examples for PromptPG at Inference time

### ISSUE THREAD

**Issue by Shivanshu-Gupta** [lupantech/PromptPG#2]
Hi,

I am working on a method for exemplar selection for in-context learning and would like to compare it with PromptPG. From my understanding of the method, the set of candidate examples is kept the same between training and inference, but this doesn't seem to be the case in the implementation (comparing [learn_policy.py:32](https://github.com/lupantech/PromptPG/blob/7cf61b1bec07222fc24b4f5a1410911f77c2d2c9/run_gpt3_rl/learn_policy.py#L32) and [run_gpt3.py:32](https://github.com/lupantech/PromptPG/tree/main/run_gpt3_rl/run_gpt3.py#L32)). Is this supposed to be the case?

Thanks,
Shivanshu

**Comment by lupantech** [comment]
Hi Shivanshu,

Thank you for reaching out. In our work, we hope that the policy network can learn to select the most suitable examples for each test example from a set of candidates. We believe that this ability can be generalized to unseen examples or different examples. To improve the final QA accuracy, it may be helpful to keep the same set of candidates during both the training and inference stages.

To implement this idea, we can make some slight edits to the code to ensure that the candidates remain fixed. If you have any questions or concerns, please don't hesitate to let me know.

Sincerely,
Pan
