### ISSUE TITLE
Many tables do not have the correct column headers

### ISSUE THREAD

**Issue by UtkarshGarg-UG** [lupantech/PromptPG#3]
Hi, thank you for the great dataset. There are some tables where the column headers are not right. The columns say "stem" and "leaf" which is not right. Some of the examples are:

![30971](https://github.com/lupantech/PromptPG/assets/10475721/8b593200-301b-4aef-8b80-d38ae69518f6)
![30972](https://github.com/lupantech/PromptPG/assets/10475721/e6781869-d778-4022-8e45-db97f6352452)
![30978](https://github.com/lupantech/PromptPG/assets/10475721/a63fc700-f9d9-48b6-a7c7-83b1e44f09f2)

**Comment by lupantech** [comment]
Thank you for your kind words and valuable feedback on the dataset!

In our approach, we employed regular regressions alongside heuristic rules to convert the raw text of tables into structured formats. Despite thorough reviews and continuous improvements to our scripts, some tables remain imperfectly parsed.

We have observed that these less accurately parsed tables, especially those with incorrect headers, do not significantly affect the models' comprehension. Moreover, as they represent a minor fraction of the total dataset, we have chosen to retain them in the current annotations. This approach aims to maintain a consistent evaluation framework for both previously tested models and those anticipated in the near future.
