### ISSUE TITLE
Something is wrong with the ranking...

### ISSUE THREAD

**Issue by zhimin-z** [lupantech/PromptPG#4]
![image](https://github.com/lupantech/PromptPG/assets/8592144/abedd853-f9e1-4e71-a91e-354d4a698480)

**Comment by lupantech** [comment]
Thanks for pointing it out. In this context, the '#' symbol refers to the model ID and is not an indicator of ranking order.

**Comment by zhimin-z** [comment]
> Thanks for pointing it out. In this context, the '#' symbol refers to the model ID and is not an indicator of ranking order.

Ok, I know. Thanks for pointing out. But it is still unintuitive to list model ID instead since this is nothing informational to outsiders. Why not list rank order instead? @lupantech

**Comment by lupantech** [comment]
We have updated the leaderboard with plenty of new models and fixed the ranks at https://promptpg.github.io/leaderboard.html. Thank you for your feedback! @zhimin-z

**Comment by zhimin-z** [comment]
> We have updated the leaderboard with plenty of new models and fixed the ranks at https://promptpg.github.io/leaderboard.html. Thank you for your feedback! @zhimin-z

That looks so nice! @lupantech
