### ISSUE TITLE
selected exemplars were similar for different questions.

### ISSUE THREAD

**Issue by IQ17** [lupantech/PromptPG#5]
Hello, I've discovered that RL chose similar exemplars even when the query questions are different based on what I've learned from both the training logs and the resulting json files. Put otherwise, a certain number of exemplars were chosen at high frequencies. 

* See shot_pids in [json](https://github.com/lupantech/PromptPG/blob/main/results/gpt3_rl/exp1_test_TQ-SA_2_seed_2.json), where "9254" and "36539" were frequently selected while "4995" was never used.
* See cids for sample[-1] in batch in [log](https://github.com/lupantech/PromptPG/blob/main/checkpoints/exp1/log.txt), where [13  1] and [1 13] were dominant.

Does this suggest that those exemplars are in any way representative of the task or dataset?

**Comment by lupantech** [comment]
Hi, Thank you for sharing your observations. The frequent selection of certain exemplars could indicate that these exemplars are highly representative of the dataset or task, suggesting their high utility in maximizing prediction rewards. However, it may raise concerns about potential overfitting or a lack of diversity in the selection process. 

To address this, it's worth investigating the characteristics of these frequently selected exemplars and considering strategies to encourage a more diverse selection, such as implementing diversity-promoting mechanisms in the policy gradient strategy. This could help in understanding whether the current selection pattern is indeed optimal or if there's room for improvement to enhance generalization.
